DELETE  http://localhost:5000/api/items/5eb23e8a111682625cde676c


GET http://localhost:5000/api/items


POST http://localhost:5000/api/items HTTP/1.1
content-type: application/json

{
    "name":"tanu"
}